INSERT INTO PUBLIC.BASE_ROLE_MENU (ID_, MENU_, ROLE_) VALUES (1, 1, 1);
INSERT INTO PUBLIC.BASE_ROLE_MENU (ID_, MENU_, ROLE_) VALUES (2, 2, 1);
INSERT INTO PUBLIC.BASE_ROLE_MENU (ID_, MENU_, ROLE_) VALUES (3, 3, 1);
INSERT INTO PUBLIC.BASE_ROLE_MENU (ID_, MENU_, ROLE_) VALUES (4, 4, 1);
INSERT INTO PUBLIC.BASE_ROLE_MENU (ID_, MENU_, ROLE_) VALUES (5, 5, 1);